#######################################################
#
# COSC 140 Homework 2, "face" problem
#
#######################################################

import turtle
from turtle import *
back=turtle.Screen()
back.bgcolor("royal blue")

import math
M = turtle.Pen()
M.width (1)
amplitude = 4
frequency = 8
M.pencolor ("blue")
M.penup()
M.goto(-400,0)
M.pendown()
for i in range (-400,400,frequency):
    y = (math.sin(i))* (2*math.pi*amplitude)+50
    M.goto(i,y)
M.hideturtle()

t = turtle.Pen()
t.pencolor("saddle brown")
t.penup()
t.goto(-150,-90)
t.pendown()
t.right(90)
t.fillcolor("saddle brown")
t.begin_fill()
for x in range(180):
    t.forward(1)
    t.right(1)
t.end_fill()
t.penup()
t.goto(-200,-90)
t.pendown()
t.forward(60)
t.pencolor("black")
t.fillcolor("crimson")
t.begin_fill()
for sides in range(3):
    t.forward(50)
    t.right(120)
t.end_fill()
t.hideturtle()

b = turtle.Pen()
b.pencolor("saddle brown")
b.right(90)
b.fillcolor("saddle brown")
b.begin_fill()
for x in range(180):
    b.forward(1)
    b.right(1)
b.end_fill()
b.penup()
b.goto(-50,0)
b.pendown()
b.forward(60)
b.pencolor("black")
b.fillcolor("green")
b.begin_fill()
for sides in range(3):
    b.forward(50)
    b.right(120)
b.end_fill()
b.hideturtle()

a = turtle.Pen()
a.pencolor("saddle brown")
a.penup()
a.goto(100,-90)
a.pendown()
a.right(90)
a.fillcolor("saddle brown")
a.begin_fill()
for x in range(180):
    a.forward(1)
    a.right(1)
a.end_fill()
a.penup()
a.goto(50,-90)
a.pendown()
a.forward(60)
a.pencolor("black")
a.fillcolor("orange")
a.begin_fill()
for sides in range(3):
    a.forward(50)
    a.right(120)
a.end_fill()
a.hideturtle()

s = turtle.Pen()
s.pencolor("yellow")
s.penup()
s.goto(270,90)
s.pendown()
s.fillcolor("yellow")
s.begin_fill()
s.circle(50)
s.end_fill()
s.hideturtle()

dock = turtle.Pen()
dock.penup()
dock.goto(200,-100)
dock.pendown()
dock.fillcolor("light gray")
dock.begin_fill()
for i in [1,2]:
  dock.forward(100)
  dock.right(90)
  dock.forward(150)
  dock.right(90)
dock.end_fill()
dock.penup()
dock.goto(200,-125)
dock.pendown()
dock.forward(100)
dock.penup()
dock.goto(200,-150)
dock.pendown()
dock.forward(100)
dock.penup()
dock.goto(200,-175)
dock.pendown()
dock.forward(100)
dock.penup()
dock.goto(200,-200)
dock.pendown()
dock.forward(100)
